[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
description = "monkey-rs"
authors = ["taga3s"]
edition = "2024"

[workspace.dependencies]
wasm-bindgen = "0.2"
